[package]
name = "dsc"
version = "0.1.0"
edition = "2021"
authors = ["longjin <longjin@DragonOS.org>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "dsc"

[dependencies]
